// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '#0a0a0a',
    player: '#00ff41',
    obstacle: '#00d4ff',
    ground: '#ff00ff',
    text: '#ffffff',
    accent: '#00ff41',
  },
  physics: {
    gravity: 0.5,
    jumpForce: -11,
    baseSpeed: 4,
    speedIncrement: 0.002,
  },
  obstacles: {
    frequency: 0.02,
    minHeight: 30,
    maxHeight: 60,
    width: 25,
    gap: 200,
  },
  player: {
    width: 40,
    height: 40,
    groundOffset: 60,
  },
  visual: {
    style: 'hand-drawn',
    cornerRadius: 12,
    shadowBlur: 10,
  },
  game: {
    title: 'Pixel Dash',
    sessionLength: 'short',
  },
};

export default config;
