import type { GameDesignSnapshot, ArenaMechanics } from '../snapshot.js';
import { escapeJsString } from './escape.js';

export function getArenaConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as ArenaMechanics;
  const c = snapshot.colorPalette;

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    player: '${c.primary}',
    enemy: '${c.accent}',
    bullet: '${c.text}',
    text: '${c.text}',
    accent: '${c.primary}',
    healthBar: '${c.primary}',
  },
  player: {
    speed: ${m.playerSpeed},
    size: 30,
    maxHealth: 5,
  },
  bullets: {
    speed: ${m.bulletSpeed},
    size: ${m.bulletSize},
    cooldown: ${m.bulletCooldown},
  },
  enemies: {
    baseSpeed: ${m.enemySpeed},
    size: 25,
    spawnRate: ${m.spawnRate},
    waveDifficultyCurve: ${m.waveDifficultyCurve},
    types: [
      { name: 'basic', hp: 1, speedMult: 1.0, sizeMult: 1.0, score: 50, colorShift: 0 },
      { name: 'tank',  hp: 3, speedMult: 0.5, sizeMult: 1.6, score: 150, colorShift: -30 },
      { name: 'fast',  hp: 1, speedMult: 2.0, sizeMult: 0.7, score: 100, colorShift: 30 },
    ],
  },
  powerups: {
    dropChance: 0.2,
    size: 14,
    lifetime: 8,
    effectDuration: 10,
    shieldHits: 3,
    weights: [0.5, 0.3, 0.2],
  },
  arena: {
    width: ${m.arenaWidth},
    height: ${m.arenaHeight},
  },
  visual: {
    style: '${snapshot.visualStyle}',
    cornerRadius: ${snapshot.visualStyle === 'pixel' ? 0 : 4},
    shadowBlur: ${snapshot.vibe === 'minimal' ? 0 : 8},
  },
  game: {
    title: '${escapeJsString(snapshot.title)}',
  },
};

export default config;
`;
}
