import type { GameDesignSnapshot, ArenaMechanics } from '../snapshot.js';

export function getArenaConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as ArenaMechanics;
  const c = snapshot.colorPalette;

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    player: '${c.primary}',
    enemy: '${c.accent}',
    bullet: '${c.text}',
    text: '${c.text}',
    accent: '${c.primary}',
    healthBar: '${c.primary}',
  },
  player: {
    speed: ${m.playerSpeed},
    size: 30,
    maxHealth: 5,
  },
  bullets: {
    speed: ${m.bulletSpeed},
    size: 5,
    cooldown: 150,
  },
  enemies: {
    baseSpeed: ${m.enemySpeed},
    size: 25,
    spawnRate: ${m.spawnRate},
    waveDifficultyCurve: ${m.waveDifficultyCurve},
  },
  arena: {
    width: ${m.arenaWidth},
    height: ${m.arenaHeight},
  },
  visual: {
    style: '${snapshot.visualStyle}',
    cornerRadius: ${snapshot.visualStyle === 'pixel' ? 0 : 4},
    shadowBlur: ${snapshot.vibe === 'minimal' ? 0 : 8},
  },
  game: {
    title: '${snapshot.title.replace(/'/g, "\\'")}',
    sessionLength: '${snapshot.sessionLength}',
  },
};

export default config;
`;
}
