import type { GameDesignSnapshot, PuzzleMechanics } from '../snapshot.js';
import { escapeJsString } from './escape.js';

export function getPuzzleConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as PuzzleMechanics;
  const c = snapshot.colorPalette;

  const pieceColors = [c.primary, c.accent, c.secondary, '#ffaa00', '#00ff41', '#ff00ff'];

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    text: '${c.text}',
    accent: '${c.primary}',
    gridBg: '${c.secondary}',
    pieces: [${pieceColors.map(pc => `'${pc}'`).join(', ')}],
  },
  grid: {
    width: ${m.gridWidth},
    height: ${m.gridHeight},
    cellSize: 60,
    padding: 4,
    matchSize: ${m.matchSize},
  },
  game: {
    title: '${escapeJsString(snapshot.title)}',
    timeLimit: ${m.timeLimit},
    difficultyProgression: ${m.difficultyProgression},
  },
  scoring: {
    matchBase: 100,
    comboMultiplier: 1.5,
    levelUpThreshold: 1000,
    timeBonusThreshold: 500,
  },
  special: {
    spawnChance: 0.05,
    bombRadius: 1,
  },
  visual: {
    style: '${snapshot.visualStyle}',
    cornerRadius: ${snapshot.visualStyle === 'pixel' ? 0 : 8},
    shadowBlur: ${snapshot.vibe === 'minimal' ? 0 : 6},
  },
  animation: {
    swapDuration: 200,
    fallDuration: 300,
    matchFlashDuration: 400,
  },
};

export default config;
`;
}
