import type { GameDesignSnapshot, RacingMechanics } from '../snapshot.js';
import { escapeJsString } from './escape.js';

export function getRacingConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as RacingMechanics;
  const c = snapshot.colorPalette;

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    track: '${c.secondary}',
    trackEdge: '${c.text}',
    player: '${c.primary}',
    opponent: '${c.accent}',
    text: '${c.text}',
    accent: '${c.primary}',
  },
  vehicle: {
    topSpeed: ${m.topSpeed},
    acceleration: ${m.acceleration},
    braking: ${m.braking},
    turnSpeed: ${m.turnSpeed},
    size: 16,
  },
  track: {
    segments: [
      { type: 'straight', length: 200 },
      { type: 'curve', angle: 90, radius: 120 },
      { type: 'straight', length: 150 },
      { type: 'curve', angle: 90, radius: 120 },
      { type: 'straight', length: 200 },
      { type: 'curve', angle: 90, radius: 120 },
      { type: 'straight', length: 150 },
      { type: 'curve', angle: 90, radius: 120 },
    ],
    width: 80,
  },
  opponents: {
    count: ${m.opponentCount},
    speedVariation: 0.1,
    rubberBanding: true,
  },
  race: {
    lapCount: ${m.lapCount},
  },
  visual: {
    style: '${snapshot.visualStyle}',
  },
  game: {
    title: '${escapeJsString(snapshot.title)}',
  },
};

export default config;
`;
}
