import type { GameDesignSnapshot, RPGMechanics } from '../snapshot.js';
import { escapeJsString } from './escape.js';

export function getRPGConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as RPGMechanics;
  const c = snapshot.colorPalette;

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    floor: '${c.secondary}',
    wall: '${c.primary}',
    player: '${c.primary}',
    enemy: '${c.accent}',
    npc: '#f0c040',
    item: '#50fa7b',
    text: '${c.text}',
    accent: '${c.accent}',
    hud: '${c.primary}',
  },
  player: {
    speed: ${m.playerSpeed},
    size: 24,
    maxHealth: ${m.playerMaxHealth},
    attackDamage: ${m.attackDamage},
    attackRange: 40,
    attackCooldown: ${m.attackCooldown},
  },
  combat: {
    invulnDuration: 1.0,
    knockback: 5,
    damageNumberDuration: 0.8,
  },
  map: {
    roomWidth: ${m.mapWidth},
    roomHeight: ${m.mapHeight},
    tileSize: 40,
    wallThickness: 40,
  },
  inventory: {
    maxSize: ${m.inventorySize},
    slotSize: 40,
  },
  visual: {
    style: '${snapshot.visualStyle}',
  },
  game: {
    title: '${escapeJsString(snapshot.title)}',
  },
  rpg: {
    startRoom: 'entrance',
    rooms: {
      entrance: {
        name: 'Entrance Hall',
        exits: { right: 'hallway' },
        enemies: [],
        items: [],
        npcs: ['elder'],
        wallColor: '#3a3a5c',
        floorColor: '#1e1e2e',
      },
      hallway: {
        name: 'Dark Hallway',
        exits: { left: 'entrance', right: 'armory', bottom: 'dungeon' },
        enemies: ['slime', 'slime'],
        items: ['potion'],
        npcs: [],
        wallColor: '#2a2a4c',
        floorColor: '#16162e',
      },
      armory: {
        name: 'Old Armory',
        exits: { left: 'hallway' },
        enemies: ['skeleton'],
        items: ['sword'],
        npcs: [],
        wallColor: '#4a3a3a',
        floorColor: '#2e1e1e',
      },
      dungeon: {
        name: 'Deep Dungeon',
        exits: { top: 'hallway' },
        enemies: ['skeleton', 'slime'],
        items: ['key', 'potion'],
        npcs: [],
        wallColor: '#1a1a3c',
        floorColor: '#0e0e1e',
      },
    },
    enemies: {
      slime: {
        name: 'Slime',
        health: 30,
        damage: 5,
        speed: 1,
        size: 20,
        color: '#44cc44',
        behavior: 'wander',
      },
      skeleton: {
        name: 'Skeleton',
        health: 50,
        damage: 10,
        speed: 2,
        size: 22,
        color: '#ccccaa',
        behavior: 'chase',
      },
    },
    items: {
      potion: {
        name: 'Health Potion',
        type: 'consumable',
        effect: 'heal',
        value: 30,
        color: '#ff4466',
      },
      sword: {
        name: 'Iron Sword',
        type: 'weapon',
        effect: 'damage',
        value: 5,
        color: '#aaaadd',
      },
      key: {
        name: 'Dungeon Key',
        type: 'quest',
        effect: 'none',
        value: 0,
        color: '#ffdd44',
      },
    },
    npcs: {
      elder: {
        name: 'Village Elder',
        dialogue: [
          'Welcome, adventurer. Dark times have fallen upon us.',
          'A cursed key lies deep in the dungeon below.',
          'Find it and bring it back here to lift the curse.',
          'Be careful — the creatures grow stronger in the depths.',
        ],
        color: '#f0c040',
      },
    },
    quest: {
      objective: 'Find the Dungeon Key and return to the Entrance Hall',
      requiredItem: 'key',
      completionRoom: 'entrance',
    },
  },
};

export default config;
`;
}
