import type { GameDesignSnapshot, RunnerMechanics } from '../snapshot.js';
import { escapeJsString } from './escape.js';

export function getRunnerConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as RunnerMechanics;
  const c = snapshot.colorPalette;

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    player: '${c.primary}',
    obstacle: '${c.accent}',
    ground: '${c.secondary}',
    text: '${c.text}',
    accent: '${c.primary}',
  },
  physics: {
    gravity: ${m.gravity},
    jumpForce: ${m.jumpForce},
    jumpForceShort: -7,
    baseSpeed: ${m.baseSpeed},
    speedIncrement: ${m.speedIncrement},
  },
  obstacles: {
    frequency: ${m.obstacleFrequency},
    minHeight: 30,
    maxHeight: 60,
    width: 25,
    gap: 200,
    nearMissMargin: 25,
    nearMissPoints: 15,
    usePatterns: true,
    types: [
      { id: 'block', width: 25, heightRange: [30, 60], color: '${c.accent}' },
      { id: 'spike', width: 30, heightRange: [35, 50], color: '#ff4444' },
      { id: 'moving', width: 25, heightRange: [30, 55], color: '${c.secondary}' },
    ],
  },
  collectibles: {
    spawnChance: 0.03,
    types: [
      { id: 'coin', points: 10, color: '#ffd700', size: 18 },
      { id: 'star', points: 50, color: '#00ffff', size: 20 },
    ],
  },
  powerups: {
    spawnChance: 0.005,
    duration: {
      shield: Infinity,
      magnet: 15000,
      slowmo: 10000,
    },
  },
  scoring: {
    timeBonus: 0.5,
    comboDecayTime: 1.5,
    comboMultiplier: 0.5,
  },
  player: {
    width: 40,
    height: 40,
    groundOffset: 60,
    doubleJump: true,
  },
  visual: {
    style: '${['nes', 'snes'].includes(snapshot.vibe) ? 'pixel' : snapshot.visualStyle}',
    cornerRadius: ${snapshot.visualStyle === 'pixel' ? 0 : snapshot.visualStyle === 'hand-drawn' ? 12 : 8},
    shadowBlur: ${snapshot.vibe === 'minimal' ? 0 : 10},
    parallaxFar: 0.25,
    parallaxNear: 0.35,
    retroEra: ${['nes', 'snes'].includes(snapshot.vibe) ? `'${snapshot.vibe}'` : 'null'},
    scanlines: ${['nes', 'snes'].includes(snapshot.vibe) ? 'true' : 'false'},
    outlineColor: '#0a0a14',
  },
  juice: {
    screenShake: true,
    shakeIntensity: 1,
    particleBurst: true,
    scorePop: true,
    hitPause: 0,
  },
  game: {
    title: '${escapeJsString(snapshot.title)}',
  },
};

export default config;
`;
}
