import type { GameDesignSnapshot, RunnerMechanics } from '../snapshot.js';

export function getRunnerConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as RunnerMechanics;
  const c = snapshot.colorPalette;

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    player: '${c.primary}',
    obstacle: '${c.accent}',
    ground: '${c.secondary}',
    text: '${c.text}',
    accent: '${c.primary}',
  },
  physics: {
    gravity: ${m.gravity},
    jumpForce: ${m.jumpForce},
    baseSpeed: ${m.baseSpeed},
    speedIncrement: ${m.speedIncrement},
  },
  obstacles: {
    frequency: ${m.obstacleFrequency},
    minHeight: 30,
    maxHeight: 60,
    width: 25,
    gap: 200,
  },
  player: {
    width: 40,
    height: 40,
    groundOffset: 60,
  },
  visual: {
    style: '${snapshot.visualStyle}',
    cornerRadius: ${snapshot.visualStyle === 'pixel' ? 0 : snapshot.visualStyle === 'hand-drawn' ? 12 : 8},
    shadowBlur: ${snapshot.vibe === 'minimal' ? 0 : 10},
  },
  game: {
    title: '${snapshot.title.replace(/'/g, "\\'")}',
    sessionLength: '${snapshot.sessionLength}',
  },
};

export default config;
`;
}
