import type { GameDesignSnapshot, StoryMechanics } from '../snapshot.js';
import { escapeJsString } from './escape.js';

export function getStoryConfig(snapshot: GameDesignSnapshot): string {
  const m = snapshot.mechanics as StoryMechanics;
  const c = snapshot.colorPalette;

  return `// Game configuration — generated by ArcadeForge
// Edit these values to customize your game

const config = {
  colors: {
    background: '${c.background}',
    text: '${c.text}',
    accent: '${c.accent}',
    choiceDefault: '${c.secondary}',
    choiceHover: '${c.primary}',
    characterName: '${c.primary}',
  },
  text: {
    speed: ${m.textSpeed},
    font: 'serif',
    fontSize: 18,
    lineHeight: 28,
    maxWidth: 700,
  },
  choices: {
    timeout: ${m.choiceTimeout},
    showTimer: ${m.choiceTimeout > 0},
    keyboardShortcuts: true,
  },
  transitions: {
    duration: ${m.sceneTransitionDuration},
    type: 'fade',
  },
  autoAdvance: {
    enabled: ${m.enableAutoAdvance},
    delay: ${m.autoAdvanceDelay},
    showIndicator: true,
  },
  saves: {
    maxSlots: ${m.maxSaveSlots},
    autosave: true,
  },
  game: {
    title: '${escapeJsString(snapshot.title)}',
  },
  story: {
    scenes: {},
    startScene: 'intro',
  },
};

export default config;
`;
}
