import { GoogleGenerativeAI } from '@google/generative-ai';
import chalk from 'chalk';
import type { GameDesignSnapshot } from './snapshot.js';

const API_KEY = process.env.GOOGLE_API_KEY;

// Base configuration schemas for the AI to fill/modify
const SCHEMAS = {
  runner: {
    colors: { background: '', player: '', obstacle: '', ground: '', text: '', accent: '' },
    physics: { gravity: 0.5, jumpForce: -11, baseSpeed: 4, speedIncrement: 0.002 },
    obstacles: { frequency: 0.02, minHeight: 30, maxHeight: 60, width: 25, gap: 200 },
    player: { width: 40, height: 40, groundOffset: 60 },
    visual: { style: 'geometric', cornerRadius: 8, shadowBlur: 10 },
    game: { title: '', sessionLength: 'medium' }
  },
  arena: {
    colors: { background: '', player: '', enemy: '', bullet: '', text: '', accent: '' },
    game: { title: '', sessionLength: 'medium' },
    player: { speed: 5, fireRate: 150, bulletSpeed: 10, health: 3 },
    enemies: { spawnRate: 60, speed: 2, size: 30, scoreValue: 100 },
    waves: { difficultyMultiplier: 1.1, timeBetweenWaves: 3000 },
    visual: { style: 'geometric', shadowBlur: 10 }
  },
  puzzle: {
    colors: { background: '', accent: '', text: '', pieces: ['', '', '', '', ''] },
    game: { title: '', timeLimit: 60, targetScore: 1000 },
    grid: { rows: 8, cols: 8, cellSize: 50, gap: 4 },
    match: { minMatch: 3, baseScore: 100 },
    visual: { style: 'geometric', cornerRadius: 8 }
  }
};

export async function generateConfigWithAI(snapshot: GameDesignSnapshot): Promise<string | null> {
  if (!API_KEY) {
    return null;
  }

  try {
    const genAI = new GoogleGenerativeAI(API_KEY);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

    console.log(chalk.blue('   ✨ Consulting the oracle (Gemini)...'));

    const schema = SCHEMAS[snapshot.genre as keyof typeof SCHEMAS];
    const prompt = `
You are a creative game designer. Generate a JSON configuration object for a browser-based "${snapshot.genre}" game.

USER REQUIREMENTS:
- Title: "${snapshot.title}"
- Vibe: "${snapshot.vibe}" (Choose colors that match this vibe perfectly)
- Difficulty: "${snapshot.difficulty}" (Adjust physics/gameplay values accordingly)
- Visual Style: "${snapshot.visualStyle}"
- Scope: "${snapshot.scope}"
- Custom Notes: "${snapshot.customNotes}"

REQUIRED SCHEMA (JSON):
${JSON.stringify(schema, null, 2)}

INSTRUCTIONS:
1. Return ONLY valid JSON. No markdown formatting, no code blocks.
2. Fill in all specific values (especially colors).
3. Adjust physics/gameplay numbers to match the requested difficulty and notes.
4. Ensure "colors" contains valid hex codes.
5. Do not add new top-level keys. You can adjust values within the existing structure.
`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    // Clean up markdown code blocks if present (e.g. ```json ... ```)
    const jsonString = text.replace(/```json/g, '').replace(/```/g, '').trim();
    
    // Validate by parsing (throws if invalid)
    JSON.parse(jsonString);

    // Convert to JS module format
    return `// Game configuration — generated by Gemini 2.0 Flash
// Vibe: ${snapshot.vibe} | Difficulty: ${snapshot.difficulty}
// "${snapshot.customNotes}"

const config = ${jsonString};

export default config;
`;

  } catch (error) {
    console.error(chalk.yellow('   ⚠️ AI generation failed, falling back to static config.'));
    // console.error(error); // debug
    return null;
  }
}

export function getChatSession(systemInstruction: string) {
  if (!API_KEY) return null;

  const genAI = new GoogleGenerativeAI(API_KEY);
  const model = genAI.getGenerativeModel({ 
    model: 'gemini-2.0-flash',
    systemInstruction
  });

  return model.startChat({
    history: [],
  });
}
