import path from 'node:path';
import fse from 'fs-extra';
import chalk from 'chalk';
import { select, confirm, input } from '@inquirer/prompts';
import { execSync, spawnSync } from 'node:child_process';
import type { GameDesignSnapshot } from './snapshot.js';

type DeployTarget = 'github-pages' | 'netlify' | 'vercel' | 'manual';

// Set ARCADEFORGE_HUB_URL in your environment to point to your production hub.
// Falls back to localhost for local development.
const HUB_API_URL = process.env.ARCADEFORGE_HUB_URL || 'https://arcadeforge-hub.vercel.app/api/submit';

const GITHUB_ACTIONS_WORKFLOW = `name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;

const NETLIFY_TOML = `[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`;

const VERCEL_JSON = `{
  "rewrites": [
    { "source": "/(.*)", "destination": "/index.html" }
  ]
}
`;

async function initGitIfNeeded(): Promise<void> {
  const gitDir = path.resolve(process.cwd(), '.git');
  if (await fse.pathExists(gitDir)) return;

  const shouldInit = await confirm({
    message: 'No git repo found. Initialize one?',
    default: true,
  });

  if (shouldInit) {
    execSync('git init', { cwd: process.cwd(), stdio: 'pipe' });
    execSync('git add -A', { cwd: process.cwd(), stdio: 'pipe' });
    execSync('git commit -m "Initial commit — generated by ArcadeForge"', {
      cwd: process.cwd(),
      stdio: 'pipe',
    });
    console.log(chalk.green('   ✓ Git initialized and first commit created'));
  }
}

async function deployGitHubPages(): Promise<void> {
  const workflowDir = path.resolve(process.cwd(), '.github', 'workflows');
  await fse.ensureDir(workflowDir);
  await fse.writeFile(
    path.join(workflowDir, 'deploy.yml'),
    GITHUB_ACTIONS_WORKFLOW,
    'utf-8',
  );
  console.log(chalk.green('   ✓ Created .github/workflows/deploy.yml'));
  console.log(chalk.bold('\n📋 Next steps:'));
  console.log('   1. Create a GitHub repo and push your code');
  console.log('   2. Go to Settings → Pages → Source: GitHub Actions');
  console.log('   3. Push to main branch to trigger deploy');
}

async function deployNetlify(): Promise<void> {
  await fse.writeFile(
    path.resolve(process.cwd(), 'netlify.toml'),
    NETLIFY_TOML,
    'utf-8',
  );
  console.log(chalk.green('   ✓ Created netlify.toml'));
  console.log(chalk.bold('\n📋 Next steps:'));
  console.log('   1. Push your code to GitHub');
  console.log('   2. Go to netlify.com → New site from Git');
  console.log('   3. Select your repo — Netlify will auto-detect the config');
}

async function deployVercel(): Promise<void> {
  await fse.writeFile(
    path.resolve(process.cwd(), 'vercel.json'),
    VERCEL_JSON,
    'utf-8',
  );
  console.log(chalk.green('   ✓ Created vercel.json'));
  console.log(chalk.bold('\n📋 Next steps:'));
  console.log('   1. Install Vercel CLI: npm i -g vercel');
  console.log('   2. Run: vercel');
  console.log('   3. Follow the prompts to deploy');
}

function generateHubSubmission(snapshot: GameDesignSnapshot): string {
  return JSON.stringify(
    {
      title: snapshot.title,
      description: snapshot.elevatorPitch,
      genre: snapshot.genre,
      tags: [snapshot.vibe, snapshot.visualStyle, snapshot.difficulty],
      creator_name: '',
      url: '',
    },
    null,
    2,
  );
}

async function submitToHub(snapshot: GameDesignSnapshot, gameUrl: string): Promise<void> {
  const creatorName = await input({
    message: 'What is your creator name (or alias)?',
    default: 'Anonymous Forge Master',
  });

  console.log(chalk.blue('   ✨ Submitting to ArcadeForge Hub...'));

  try {
    const response = await fetch(HUB_API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: snapshot.title,
        description: snapshot.elevatorPitch,
        url: gameUrl,
        genre: snapshot.genre,
        creator_name: creatorName,
        tags: [snapshot.vibe, snapshot.visualStyle, snapshot.difficulty],
      }),
    });

    if (response.ok) {
      console.log(chalk.bold.green('   🎉 Game submitted! It will appear on the Hub after moderation.'));
    } else {
      const err = await response.json();
      throw new Error(err.error || 'Submission failed');
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    console.log(chalk.yellow(`   ⚠️ Could not auto-submit to Hub: ${msg}`));
    console.log(chalk.dim('   You can still submit manually at the website.'));
  }
}

export async function runDeploy(): Promise<void> {
  const snapshotPath = path.resolve(process.cwd(), 'game-snapshot.json');

  if (!await fse.pathExists(snapshotPath)) {
    console.log(chalk.red('No game-snapshot.json found in current directory.'));
    process.exit(1);
  }

  const snapshot: GameDesignSnapshot = await fse.readJSON(snapshotPath);

  console.log(chalk.bold.cyan(`\n🚀 Deploy — ${snapshot.title}`));

  const target = await select<DeployTarget>({
    message: 'How would you like to deploy?',
    choices: [
      { value: 'vercel', name: 'Vercel (Recommended — fastest one-click)' },
      { value: 'github-pages', name: 'GitHub Pages (Config only)' },
      { value: 'netlify', name: 'Netlify (Config only)' },
      { value: 'manual', name: 'I have already deployed (Just submit to Hub)' },
    ],
  });

  let deployedUrl = '';

  if (target === 'vercel') {
    const hasVercel = spawnSync('vercel', ['--version']).status === 0;
    
    if (hasVercel) {
      const proceed = await confirm({
        message: 'Vercel CLI detected. Deploy now?',
        default: true,
      });

      if (proceed) {
        console.log(chalk.blue('   📦 Deploying via Vercel CLI...'));
        try {
          // vercel --prod --confirm returns the URL in stdout
          const result = execSync('vercel --prod --yes', { stdio: 'pipe' }).toString();
          const urlMatch = result.match(/https:\/\/[a-z0-9-]+\.vercel\.app/i);
          if (urlMatch) {
            deployedUrl = urlMatch[0];
            console.log(chalk.green(`   ✓ Live at: ${deployedUrl}`));
          }
        } catch (err: unknown) {
          console.log(chalk.red('   ❌ Vercel deploy failed. Falling back to config generation.'));
          if (err instanceof Error) console.log(chalk.dim(err.message));
        }
      }
    }
    
    if (!deployedUrl) {
      await deployVercel();
    }
  } else if (target === 'github-pages') {
    await initGitIfNeeded();
    await deployGitHubPages();
  } else if (target === 'netlify') {
    await deployNetlify();
  } else if (target === 'manual') {
    deployedUrl = await input({
      message: 'Enter your live game URL:',
      validate: (val) => val.startsWith('http') || 'Please enter a valid URL',
    });
  }

  if (deployedUrl) {
    const shouldSubmit = await confirm({
      message: 'Would you like to submit your game to the ArcadeForge Hub now?',
      default: true,
    });

    if (shouldSubmit) {
      await submitToHub(snapshot, deployedUrl);
    }
  }
}
